In [46]:
import pandas as pd

In [116]:
df = pd.read_csv('data.csv')

In [48]:
# 1.
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [49]:
# 2.
df.dropna()
# Drop rows with *any* missing values

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [50]:
df.dropna(axis=1)
#  Drop columns with missing values

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [51]:
# 3.
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [52]:
df.fillna(method="ffill")

C:\Users\zalte\AppData\Local\Temp\ipykernel_14876\3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [53]:
df.fillna(method="bfill")

C:\Users\zalte\AppData\Local\Temp\ipykernel_14876\3896554658.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [54]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [55]:

# 5
df.duplicated() # True for duplicates

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [56]:
df.drop_duplicates()
# Remove duplicate rows

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [57]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [58]:
# 6.
df.duplicated(subset=["Name", "Age"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [59]:
# 7.
df['Name'].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [60]:
# 8.
df['City'].str.contains('delhi',case=False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [61]:
# 9.
df['Email'].str.split('@')

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [62]:
df2 = df.dropna().copy()

In [63]:
df2['Age'] = df2['Age'].astype(int)

In [64]:
df2['Age'].astype

<bound method NDFrame.astype of 0    25
2    30
4    22
6    25
7    25
Name: Age, dtype: int64>

In [65]:
# 10.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       8 non-null      object
 1   Age        6 non-null      float64
 2   City       9 non-null      object
 3   Gender     9 non-null      object
 4   Email      9 non-null      object
 5   Join Date  8 non-null      object
dtypes: float64(1), object(5)
memory usage: 564.0+ bytes

In [66]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Age        5 non-null      int64
 2   City       5 non-null      object
 3   Gender     5 non-null      object
 4   Email      5 non-null      object
 5   Join Date  5 non-null      object
dtypes: int64(1), object(5)
memory usage: 280.0+ bytes

In [97]:
# 12.
df2 = df.dropna().copy()

In [68]:
df2

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [69]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [70]:
# 13.
df["Age Group"] = df["Age"].apply(lambda x : 'Adult' if x >= 25 else 'Minor')

In [71]:
df

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Minor
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Adult
6    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor

    Name   Age         City  Gender              Email   Join Date
0  Alice  25.0     New York  Female  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020
4  David  22.0       Mumbai    Male  david@example.com  12-11-2019
6  Alice  25.0     New York  Female  alice@example.com  01-05-2021
7  Alice  25.0     New York  Female  alice@example.com  01-05-2021

In [76]:
# 15.
gender_map = {"M": "Male", "F": "Female", "O": "Other"}
df2["Gender"] = df2["Gender"].map(gender_map)

In [77]:
df2

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York    NaN  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles    NaN    bob@example.com  15-06-2020
4  David  22.0       Mumbai    NaN  david@example.com  12-11-2019
6  Alice  25.0     New York    NaN  alice@example.com  01-05-2021
7  Alice  25.0     New York    NaN  alice@example.com  01-05-2021

In [92]:
# 16.
df2["City"] = df2["City"].replace({
    'del':'Delhi',
    'mum':'New Mumbai',
})

In [93]:
df2

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York    NaN  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles    NaN    bob@example.com  15-06-2020
4  David  22.0   New Mumbai    NaN  david@example.com  12-11-2019
6  Alice  25.0     New York    NaN  alice@example.com  01-05-2021
7  Alice  25.0     New York    NaN  alice@example.com  01-05-2021

In [94]:
# 17.
df.sort_values("Age")

      Name   Age         City Gender              Email   Join Date Age Group
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Minor
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
6    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Adult
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor

In [101]:
# 18.
df2.sort_values(["City", "Age"])

    Name   Age         City Gender              Email   Join Date Age Group
1    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
2  David  22.0       Mumbai      M  david@example.com  12-11-2019     Minor
0  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
3  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
4  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult

In [104]:
 
# 19.
df2.reset_index(drop=True, inplace=True)

In [105]:
df2

    Name   Age         City Gender              Email   Join Date Age Group
0  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
2  David  22.0       Mumbai      M  david@example.com  12-11-2019     Minor
3  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
4  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult

In [ ]:
# 20.
df2.sort_index()

    Name   Age         City Gender              Email   Join Date Age Group
0  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
2  David  22.0       Mumbai      M  david@example.com  12-11-2019     Minor
3  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
4  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult

In [ ]:
# 21.
b = df2['Age Rank'] = df2['Age'].rank(method='dense', ascending=False)

In [110]:
b

0    2.0
1    1.0
2    3.0
3    2.0
4    2.0
Name: Age, dtype: float64

In [114]:
# 22.
df2 = df[["City", "Name", "Age"]]

In [115]:
df2

          City     Name   Age
0     New York    Alice  25.0
1        Delhi  Charlie   NaN
2  Los Angeles      Bob  30.0
3        Delhi  Charlie   NaN
4       Mumbai    David  22.0
5        Delhi      NaN  28.0
6     New York    Alice  25.0
7     New York    Alice  25.0
8        Delhi  Charlie   NaN

In [123]:
# 23.
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}
dfx = pd.DataFrame(data)

In [129]:
# 24.
dfx_melted = pd.melt(
    dfx,
    id_vars=['Name'],
    value_vars=['Math', 'Science', 'English'],
    var_name='Subject',
    value_name='Score'
)

In [131]:
dfx_melted

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [135]:
# 24.
dfx_melted.pivot(
    index='Name',
    columns='Subject',
    values='Score'
)

Subject  English  Math  Science
Name
Alice         88    85       90
Bob           85    78       82
Charlie       94    92       89