In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("data.csv")

In [6]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [12]:
# 1.
df.loc[0:4]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0

In [13]:
# 2.

df[["Actor","Year","IMDb"]]

                 Actor  Year  IMDb
0       Shah Rukh Khan  2023   7.2
1          Salman Khan  2017   6.0
2           Aamir Khan  2016   8.4
3        Ranbir Kapoor  2022   5.6
4        Ranveer Singh  2018   7.0
5   Ayushmann Khurrana  2018   8.3
6        Rajkummar Rao  2018   7.5
7       Hrithik Roshan  2019   6.5
8         Akshay Kumar  2019   7.0
9        Kartik Aaryan  2022   5.9
10        Varun Dhawan  2017   6.1
11       Vicky Kaushal  2019   8.2

In [40]:
# 3.

filtered_df=df[(df["IMDb"]>7.5) & (df["Year"]>= 2010)]

In [41]:
filtered_df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [43]:
# 4.

filtered_df.to_csv("filtered_movies.csv", index=False)

In [52]:
# 5.

import pandas as pd

# Read the Sales sheet from report.xlsx
df = pd.read_excel("report1.xlsx", sheet_name="Sales")

# Display DataFrame information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  0 non-null      float64
 1   Unnamed: 1  2 non-null      object
 2   Unnamed: 2  2 non-null      object
dtypes: float64(1), object(2)
memory usage: 204.0+ bytes

In [1]:
# 6.

import pandas as pd

# Example DataFrames
summary_df = pd.DataFrame({
    "Product": ["A", "B"],
    "Sales": [100, 200]
})

details_df = pd.DataFrame({
    "Product": ["A", "A", "B"],
    "Region": ["North", "South", "East"],
    "Sales": [50, 50, 200]
})

# Write to Excel with multiple sheets
with pd.ExcelWriter("report_out.xlsx") as writer:
    summary_df.to_excel(writer, sheet_name="Summary", index=False)
    details_df.to_excel(writer, sheet_name="Details", index=False)

print("report_out.xlsx created successfully.")

report_out.xlsx created successfully.

In [3]:
# 7. 

import pandas as pd

df = pd.json_normalize(data)

print(df)

   id name address.city address.state
0   1   Om       Mumbai   Maharashtra
1   2  Raj         Pune   Maharashtra

In [31]:
# 8. 

df = pd.DataFrame({
    "Team": ["A","A","B","B","C","C"],
    "Department": ["computer","electrical","mechanical","civil","mechatronics","AI"],
    "Salary": [40000,30000,20000,15000,10000,100000]
})
print(df)

  Team    Department  Salary
0    A      computer   40000
1    A    electrical   30000
2    B    mechanical   20000
3    B         civil   15000
4    C  mechatronics   10000
5    C            AI  100000

In [32]:
df.groupby("Department")["Salary"].mean()

Department
AI              100000.0
civil            15000.0
computer         40000.0
electrical       30000.0
mechanical       20000.0
mechatronics     10000.0
Name: Salary, dtype: float64

In [34]:
# 9. 
df.groupby("Team")["Salary"].min()

Team
A    30000
B    15000
C    10000
Name: Salary, dtype: int64

In [35]:
df.groupby("Team")["Salary"].max()

Team
A     40000
B     20000
C    100000
Name: Salary, dtype: int64

In [36]:
df.groupby("Team")["Salary"].count()

Team
A    2
B    2
C    2
Name: Salary, dtype: int64

In [37]:
df.groupby("Team")["Salary"].mean()

Team
A    35000.0
B    17500.0
C    55000.0
Name: Salary, dtype: float64

In [40]:
# 10. 

df["Team_Avg"]= df.groupby("Team")["Salary"].transform("mean")

In [44]:
print(df["Team_Avg"])

0    35000.0
1    35000.0
2    17500.0
3    17500.0
4    55000.0
5    55000.0
Name: Team_Avg, dtype: float64

In [56]:
# 11.
df.groupby("Team").filter(lambda x:x["Salary"].mean()> 80)

  Team    Department  Salary  Team_Avg
0    A      computer   40000   35000.0
1    A    electrical   30000   35000.0
2    B    mechanical   20000   17500.0
3    B         civil   15000   17500.0
4    C  mechatronics   10000   55000.0
5    C            AI  100000   55000.0

In [57]:
def team_filter(x):
    if x["Salary"].mean() > 80:
         return True
filtered_df = df.groupby("Team").filter(team_filter)

In [58]:
filtered_df

  Team    Department  Salary  Team_Avg
0    A      computer   40000   35000.0
1    A    electrical   30000   35000.0
2    B    mechanical   20000   17500.0
3    B         civil   15000   17500.0
4    C  mechatronics   10000   55000.0
5    C            AI  100000   55000.0

In [67]:
#  12.
Employees = pd.DataFrame({
   "EmpID": [1,2,3],
    "Name": ["A","B","C"],
    "DptID": [10,20,30]
})

Department= pd.DataFrame({
    "DptID": [10,20,30], 
    "DeptName": ["HR","Engineering","Marketing"]
 })

In [69]:
pd.merge(Employees, Department, on = "DptID")

   EmpID Name  DptID     DeptName
0      1    A     10           HR
1      2    B     20  Engineering
2      3    C     30    Marketing

In [74]:
# 13.

import pandas as pd

# Left join employees with departments
result = Employees.merge(Department, on="DptID", how="left")
result

   EmpID Name  DptID     DeptName
0      1    A     10           HR
1      2    B     20  Engineering
2      3    C     30    Marketing

In [75]:
# Replace missing DeptName values
result["DeptName"] = result["DeptName"].fillna("Unknown")

print(result)

   EmpID Name  DptID     DeptName
0      1    A     10           HR
1      2    B     20  Engineering
2      3    C     30    Marketing

In [2]:
# 14. 

import pandas as pd

# January data
df_jan = pd.DataFrame({
    "ID": [1, 2, 3],
    "Sales": [100, 200, 150]
})

# February data
df_feb = pd.DataFrame({
    "ID": [4, 5, 6],
    "Sales": [180, 220, 170]
})

print("January DataFrame:")
print(df_jan)

print("\nFebruary DataFrame:")
print(df_feb)

January DataFrame:
   ID  Sales
0   1    100
1   2    200
2   3    150

February DataFrame:
   ID  Sales
0   4    180
1   5    220
2   6    170

In [3]:
combined_df = pd.concat([df_jan, df_feb], ignore_index=True)

print(combined_df)

   ID  Sales
0   1    100
1   2    200
2   3    150
3   4    180
4   5    220
5   6    170

In [5]:
# 15.

df_ids = pd.DataFrame({
    "ID": [101, 102, 103]
})

df_scores = pd.DataFrame({
    "Score": [85, 90, 78]
})

combined_df = pd.concat([df_ids, df_scores], axis=1)

print(combined_df)

    ID  Score
0  101     85
1  102     90
2  103     78

In [7]:
# 16.

import pandas as pd

# Create left_df
left_df = pd.DataFrame({
    "user_id": [1, 2, 3, 4],
    "name": ["Om", "Raj", "Sam", "Amit"]
})

# Create right_df
right_df = pd.DataFrame({
    "id": [1, 2, 4],
    "score": [85, 90, 95]
})

# Left join
result = pd.merge(
    left_df,
    right_df,
    left_on="user_id",
    right_on="id",
    how="left"
)

print(result)

   user_id  name   id  score
0        1    Om  1.0   85.0
1        2   Raj  2.0   90.0
2        3   Sam  NaN    NaN
3        4  Amit  4.0   95.0

In [1]:
# 17.

import pandas as pd

df = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "East", "East"],
    "Product": ["A", "B", "A", "B", "A", "B"],
    "Sales": [100, 150, 200, 250, 300, 350]
})


result = df.groupby(["Region", "Product"])["Sales"].sum().unstack()

print(result)

Product    A    B
Region
East     300  350
North    100  150
South    200  250

In [2]:
# 18.

import pandas as pd

df = pd.DataFrame({
    "JoinDate": ["2026-01-10", "2026-01-15", "2026-02-05",
                 "2026-02-20", "2026-03-12"]
})

# Convert to datetime
df["JoinDate"] = pd.to_datetime(df["JoinDate"])

# Count rows per month
result = df.groupby(df["JoinDate"].dt.to_period("M")).size()

print(result)

JoinDate
2026-01    2
2026-02    2
2026-03    1
Freq: M, dtype: int64

In [4]:
# 19.

import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    "Name": ["Om", "Raj", "Sam"],
    "Age": [21, 22, 23],
    "City": ["Pune", "Mumbai", "Nashik"]
})

# Select columns
subset_df = df[["Name", "Age"]]

# Export to JSON
subset_df.to_json("out.json", orient="records")

print("out.json created successfully.")

out.json created successfully.

In [6]:
df[["Name", "Age"]].to_json("out.json", orient="records")