# Creating DataFrames

### From Python Lists

In [17]:
import pandas as pd

data = (["gauri", 24],["Om ", 16],["Parag", 28])

In [18]:
data

(['gauri', 24], ['Om ', 16], ['Parag', 28])

In [21]:
df = pd.DataFrame(l1, columns=["Name","DOB"])

In [22]:
df

    Name  DOB
0  gauri   24
1    Om    16
2  Parag   28

### From Dictionary of Lists

In [23]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}

df = pd.DataFrame(data)

In [24]:
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

### From NumPy Arrays

In [2]:
import numpy as np
import pandas as pd

In [7]:
arr=np.array([[2,3,5],[4,5,7]])

In [8]:
arr

array([[2, 3, 5],
       [4, 5, 7]])

In [11]:
df = pd.DataFrame(arr, columns=["A", "B","C"])

In [12]:
df

   A  B  C
0  2  3  5
1  4  5  7

### From CSV files

In [ ]:
df = pd.read_csv("data.csv" ,usecols=["A", "B"])

### From Excel Files

In [ ]:
df = pd.read_excel("data1.xlsx")

### From the Web (Example: CSV from URL)

In [35]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

In [36]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### EDA (Exploratory Data Analysis)
Exploratory Data Analysis (EDA) is an essential first step in any data science project.

- df.head()             
- df.tail()            
- df.info()           
- df.describe()        
- df.columns          
- ndf.shape

In [39]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [40]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [42]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [43]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [46]:
df.shape

(244, 7)