# Data Selection & Filtering
### Selecting Rows & Columns
**Selecting Columns**

In [2]:
import pandas as pd

In [3]:
df= pd.read_csv("data.csv")

In [4]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [6]:
df["Actor"]        # Single column (as Series)

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [7]:
df[["Actor", "Genre"]]

                 Actor            Genre
0       Shah Rukh Khan           Action
1          Salman Khan           Action
2           Aamir Khan        Biography
3        Ranbir Kapoor          Fantasy
4        Ranveer Singh       Historical
5   Ayushmann Khurrana         Thriller
6        Rajkummar Rao    Horror Comedy
7       Hrithik Roshan           Action
8         Akshay Kumar           Comedy
9        Kartik Aaryan    Horror Comedy
10        Varun Dhawan  Romantic Comedy
11       Vicky Kaushal           Action

### Selecting Rows by Index
**.loc[]**  (label-based) <br >   **.iloc[]** (position-based):

In [21]:
df.loc[0,"Actor"]   # Value at row 0, column 'Actor'

'Shah Rukh Khan'

In [22]:
df.iloc[0,1]    # Value at row 0, column at index 1

'Pathaan'

In [24]:
df.loc[0:2, ["Actor", "Genre"]]   # Rows 0 to 2, selected columns

            Actor      Genre
0  Shah Rukh Khan     Action
1     Salman Khan     Action
2      Aamir Khan  Biography

In [25]:
df.iloc[0:2, 0:2]                 # Rows and cols by index position

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai

### Fast Access: .at and .iat
These are optimized for single element access:

In [26]:
df.at[0, "Actor"]       # Fast label-based access

'Shah Rukh Khan'

In [27]:
df.iat[0, 1]           # Fast position-based access

'Pathaan'

### Filtering with Conditions
**Simple Condition**

In [30]:
df[df["Year"] > 2020]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

**Multiple Conditions (AND / OR)**

In [32]:
df[(df["Year"] > 2000) & (df["Genre"] == "Action")]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
7,Hrithik Roshan,War,2019,Action,475,6.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [36]:
df[(df["Actor"] == "Shah Rukh Khan") | (df["Year"] <2000 )]

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

### Querying with .query()

In [37]:
df.query("Year > 2000 and Genre == 'Action'")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
7,Hrithik Roshan,War,2019,Action,475,6.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [40]:
col = "Year"
df.query(f"{col} > 2019")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

### 1. Column names become variables
You can reference column names directly in the query string:

In [41]:
df.query("Year > 2019 and Genre == 'Action'")

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

### 2. String values must be in quotes
Use single or double quotes around strings in the expression:

In [44]:
df.query("Actor == 'Salman Khan'")

         Actor             Film  Year   Genre  BoxOffice(INR Crore)  IMDb
1  Salman Khan  Tiger Zinda Hai  2017  Action                   565   6.0

In [45]:
#If you have quotes inside quotes, mix them:

df.query('Genre == "Horror Comedy"')

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

### 3. Use backticks for column names with spaces or special characters
If a column name has spaces, use backticks (`):

In [48]:
df.query("`Actor` == 'Rajkummar Rao'")

           Actor   Film  Year          Genre  BoxOffice(INR Crore)  IMDb
6  Rajkummar Rao  Stree  2018  Horror Comedy                   180   7.5

### 4. You can use @ to reference Python variables
To pass external variables into .query():

In [51]:
Year_limit = 2019
df.query("Year > @Year_limit")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

### 5. Logical operators
Use these:

and, or, not — instead of &, |, ~ <br>

==, !=, <, >, <=, >=

In [55]:
df.query("Year > 2019 and Genre == 'Action'")

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

### 6. Chained comparisons
Just like Python:

In [56]:
df.query("2019 < Year <= 2025")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

### 7. Avoid using reserved keywords as column names
If you have a column named class, lambda, etc., you’ll need to use backticks:

In [57]:
df.query("`Genre` == 'Action'")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
7,Hrithik Roshan,War,2019,Action,475,6.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

### 8. Case-sensitive
Column names and string values are case-sensitive:

In [62]:
df.query("Genre == 'action'")       # ❌ if actual value is 'Action'

Empty DataFrame
Columns: [Actor, Film, Year, Genre, BoxOffice(INR Crore), IMDb]
Index: []

### 9. .query() returns a copy, not a view
The result is a new DataFrame. Changes won't affect the original unless reassigned:

In [12]:
filtered = df.query("IMDb < 7")

In [13]:
print(filtered)

             Actor                   Film  Year            Genre  \
1      Salman Khan        Tiger Zinda Hai  2017           Action
3    Ranbir Kapoor             Brahmastra  2022          Fantasy
7   Hrithik Roshan                    War  2019           Action
9    Kartik Aaryan      Bhool Bhulaiyaa 2  2022    Horror Comedy
10    Varun Dhawan  Badrinath Ki Dulhania  2017  Romantic Comedy

    BoxOffice(INR Crore)  IMDb
1                    565   6.0
3                    431   5.6
7                    475   6.5
9                    266   5.9
10                   201   6.1

In [16]:
filtered_movies = df[df['IMDb'] > 8][['Film', 'IMDb']]
print(filtered_movies)

                        Film  IMDb
2                     Dangal   8.4
5                  Andhadhun   8.3
11  Uri: The Surgical Strike   8.2