# Data Cleaning and Preprocessing

In [53]:
import pandas as pd

In [54]:
df = pd.read_csv("Data cleaning and preprocessing.csv")

In [55]:
df

                      Name  subject  Marks
0  gauri sanjivan naikwadi     math   89.0
1             khushi pawar      NaN   80.0
2        sanskruti sonwane  marathi   69.0
3             neha gaikwad  science   98.0
4             shruti nikam     math    NaN

### check missing data

In [56]:
df.isnull()

    Name  subject  Marks
0  False    False  False
1  False     True  False
2  False    False  False
3  False    False  False
4  False    False   True

In [57]:
df.isnull().sum()

Name       0
subject    1
Marks      1
dtype: int64

### drop missing data

In [58]:
df.dropna()

                      Name  subject  Marks
0  gauri sanjivan naikwadi     math   89.0
2        sanskruti sonwane  marathi   69.0
3             neha gaikwad  science   98.0

In [59]:
df.dropna(axis=1)

                      Name
0  gauri sanjivan naikwadi
1             khushi pawar
2        sanskruti sonwane
3             neha gaikwad
4             shruti nikam

### fill missing data

In [60]:
df.fillna(0)

                      Name  subject  Marks
0  gauri sanjivan naikwadi     math   89.0
1             khushi pawar        0   80.0
2        sanskruti sonwane  marathi   69.0
3             neha gaikwad  science   98.0
4             shruti nikam     math    0.0

In [61]:
df.fillna("nothing")

                      Name  subject    Marks
0  gauri sanjivan naikwadi     math     89.0
1             khushi pawar  nothing     80.0
2        sanskruti sonwane  marathi     69.0
3             neha gaikwad  science     98.0
4             shruti nikam     math  nothing

In [62]:
df["Marks"].fillna(df["Marks"].mean())

0    89.0
1    80.0
2    69.0
3    98.0
4    84.0
Name: Marks, dtype: float64

In [63]:
df.ffill()        #forward fill

                      Name  subject  Marks
0  gauri sanjivan naikwadi     math   89.0
1             khushi pawar     math   80.0
2        sanskruti sonwane  marathi   69.0
3             neha gaikwad  science   98.0
4             shruti nikam     math   98.0

In [64]:
df.bfill()          #backward fill

                      Name  subject  Marks
0  gauri sanjivan naikwadi     math   89.0
1             khushi pawar  marathi   80.0
2        sanskruti sonwane  marathi   69.0
3             neha gaikwad  science   98.0
4             shruti nikam     math    NaN

### Detecting and Removing Duplicates

In [65]:
df.duplicated()         #return booleans: true for duplicates

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [66]:
df.drop_duplicates()    #remove duplicate rows

                      Name  subject  Marks
0  gauri sanjivan naikwadi     math   89.0
1             khushi pawar      NaN   80.0
2        sanskruti sonwane  marathi   69.0
3             neha gaikwad  science   98.0
4             shruti nikam     math    NaN

In [67]:
df.duplicated(subset=["Name","Marks"])

0    False
1    False
2    False
3    False
4    False
dtype: bool

### String operations with  .str

In [68]:
df["Name"].str.lower()           #convert all names to lowercase

0    gauri sanjivan naikwadi
1               khushi pawar
2          sanskruti sonwane
3               neha gaikwad
4               shruti nikam
Name: Name, dtype: object

In [69]:
df["subject"].str.contains("math", case=False)

0     True
1      NaN
2    False
3    False
4     True
Name: subject, dtype: object

In [70]:
df["subject"].str.split("@")

0       [math]
1          NaN
2    [marathi]
3    [science]
4       [math]
Name: subject, dtype: object

### Type conversion with  .astype()

In [72]:
df["Marks"]=df["Marks"].astype(float)

In [73]:
df

                      Name  subject  Marks
0  gauri sanjivan naikwadi     math   89.0
1             khushi pawar      NaN   80.0
2        sanskruti sonwane  marathi   69.0
3             neha gaikwad  science   98.0
4             shruti nikam     math    NaN

In [75]:
df["Marks"]=pd.to_datetime(df["Marks"])

In [76]:
df

                      Name  subject                         Marks
0  gauri sanjivan naikwadi     math 1970-01-01 00:00:00.000000089
1             khushi pawar      NaN 1970-01-01 00:00:00.000000080
2        sanskruti sonwane  marathi 1970-01-01 00:00:00.000000069
3             neha gaikwad  science 1970-01-01 00:00:00.000000098
4             shruti nikam     math                           NaT

In [82]:
df["category"]=df["category"].astype("category")

In [83]:
df

                      Name  subject                         Marks category
0  gauri sanjivan naikwadi     math 1970-01-01 00:00:00.000000089     math
1             khushi pawar      NaN 1970-01-01 00:00:00.000000080      NaN
2        sanskruti sonwane  marathi 1970-01-01 00:00:00.000000069  marathi
3             neha gaikwad  science 1970-01-01 00:00:00.000000098  science
4             shruti nikam     math                           NaT     math

**check datatypes**

In [84]:
df.dtypes

Name                object
subject           category
Marks       datetime64[ns]
category          category
dtype: object

### Applying functions