# Data Transformation

## Sorting & Ranking
###  Sort by Values

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("data.csv")

In [5]:
df.sort_values("Year")                   # Ascending sort

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [7]:
df.sort_values("Year", ascending=False)     # Descending

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

### Reset Index
If you want the index to start from 0 and be sequential, you can reset it using reset_index()

In [8]:
df.reset_index(drop=True, inplace=True)     # Reset the index and drop the old index

In [10]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [11]:
df.sort_index()    #sort by index

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

## Ranking

In [13]:
df["rank"] = df["IMDb"].rank()                 # Default: average method

In [14]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,8.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,12.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,11.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,9.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,10.0

In [15]:
df["Rank"] = df["IMDb"].rank(method="dense")   # 1, 2, 2, 3

In [16]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,rank,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,8.0,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0,3.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,12.0,11.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0,1.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,11.0,10.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,9.0,8.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0,5.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0,2.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0,4.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,10.0,9.0

### Renaming Columns & Index

In [17]:
df.rename(columns={"oldName": "newName"}, inplace=True)

In [18]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,rank,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,8.0,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0,3.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,12.0,11.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0,1.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,11.0,10.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,9.0,8.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0,5.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0,2.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0,4.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,10.0,9.0

In [19]:
df.rename(index={0: "row1", 1: "row2"}, inplace=True)

In [20]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,rank,Rank
row1,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,8.0,7.0
row2,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0,3.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,12.0,11.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0,1.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,11.0,10.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,9.0,8.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0,5.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0,2.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0,4.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,10.0,9.0

In [25]:
df.columns = ["Actor", "Year","Film", "IMDb","Genre","BoxOffice(INR Crore)","rank","Rank"]

In [26]:
df

,Actor,Year,Film,IMDb,Genre,BoxOffice(INR Crore),rank,Rank
row1,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,8.0,7.0
row2,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0,3.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,12.0,11.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0,1.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,11.0,10.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,9.0,8.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0,5.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0,2.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0,4.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,10.0,9.0

### Changing Column Order
Just pass a new list of column names:

In [27]:
df = df[["Actor", "Year","Film", "IMDb","Genre","BoxOffice(INR Crore)","rank","Rank"]]   # Reorder as desired

In [28]:
df

,Actor,Year,Film,IMDb,Genre,BoxOffice(INR Crore),rank,Rank
row1,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,8.0,7.0
row2,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0,3.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,12.0,11.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0,1.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,11.0,10.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,9.0,8.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0,5.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0,2.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0,4.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,10.0,9.0

In [29]:
cols = ["Actor"] + [col for col in df.columns if col != "Actor"]
df = df[cols]

In [30]:
df

,Actor,Year,Film,IMDb,Genre,BoxOffice(INR Crore),rank,Rank
row1,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,8.0,7.0
row2,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0,3.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,12.0,11.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0,1.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,11.0,10.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,9.0,8.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0,5.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0,2.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0,4.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,10.0,9.0

In [2]:
import pandas as pd
df = pd.read_csv("data.csv")
selected_columns = df[['Film', 'IMDb']].copy()
selected_columns.loc[0, 'IMDb'] = 10.0
print(selected_columns)

                        Film  IMDb
0                    Pathaan  10.0
1            Tiger Zinda Hai   6.0
2                     Dangal   8.4
3                 Brahmastra   5.6
4                  Padmaavat   7.0
5                  Andhadhun   8.3
6                      Stree   7.5
7                        War   6.5
8                 Good Newwz   7.0
9          Bhool Bhulaiyaa 2   5.9
10     Badrinath Ki Dulhania   6.1
11  Uri: The Surgical Strike   8.2

In [3]:
print(df)

                 Actor                      Film  Year            Genre  \
0       Shah Rukh Khan                   Pathaan  2023           Action
1          Salman Khan           Tiger Zinda Hai  2017           Action
2           Aamir Khan                    Dangal  2016        Biography
3        Ranbir Kapoor                Brahmastra  2022          Fantasy
4        Ranveer Singh                 Padmaavat  2018       Historical
5   Ayushmann Khurrana                 Andhadhun  2018         Thriller
6        Rajkummar Rao                     Stree  2018    Horror Comedy
7       Hrithik Roshan                       War  2019           Action
8         Akshay Kumar                Good Newwz  2019           Comedy
9        Kartik Aaryan         Bhool Bhulaiyaa 2  2022    Horror Comedy
10        Varun Dhawan     Badrinath Ki Dulhania  2017  Romantic Comedy
11       Vicky Kaushal  Uri: The Surgical Strike  2019           Action

    BoxOffice(INR Crore)  IMDb
0                   1050   7.2
1                    565   6.0
2                   2024   8.4
3                    431   5.6
4                    585   7.0
5                    111   8.3
6                    180   7.5
7                    475   6.5
8                    318   7.0
9                    266   5.9
10                   201   6.1
11                   342   8.2