# Merging & Joining Data

In [1]:
import pandas as pd
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [2]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [3]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

### Merge Like SQL: pd.merge()
Inner Join (default)

In [5]:
pd.merge(employees, departments, on="DeptID")      #Returns only matching DeptIDs:

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

### Left Join
Keeps all employees, fills NaN where no match.

In [6]:
pd.merge(employees, departments, on="DeptID", how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

### Right Join
Keeps all departments, even if no employee.

In [7]:
pd.merge(employees, departments, on="DeptID", how="right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

### Outer join
Includes all data, fills missing with NaN.

In [8]:
pd.merge(employees, departments, on="DeptID", how="outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

## Concatenating DataFrames
Use pd.concat() to stack datasets either vertically or horizontally.

In [16]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

In [17]:
df1

    Name
0  Alice
1    Bob

In [18]:
df2

      Name
0  Charlie
1    David

In [19]:
pd.concat([df1, df2])          # vertical (rows)

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [12]:
df1 = pd.DataFrame({"ID": [1, 2]})
df2 = pd.DataFrame({"Score": [90, 80]})

In [13]:
df1

   ID
0   1
1   2

In [14]:
df2

   Score
0     90
1     80

In [15]:
pd.concat([df1, df2], axis=1)        # horizontal (columns)

   ID  Score
0   1     90
1   2     80